### ISSUE TITLE
Bugs when net exception

### ISSUE THREAD

**Issue by bobozdb** [codebrainz/ftplib#1]
while the ftp is updownloading, unplug the EthernetCable, the program will be blocked even though use FtpSetCallback and set idletime 30’s

**Comment by bobozdb** [comment]
vertion num is ftplib4.0, i have get the lastest ftplib4.0-1, but this bug not be closed

**Comment by codebrainz** [comment]
I would suggest to contact Thomas, the author of [ftplib](http://nbpfaus.net/~pfau/ftplib/). This repository is an outdated copy that I had used, where I made it use a different build system. Sorry for the confusion.
