### ISSUE TITLE
Is this work on Windows?

### ISSUE THREAD

**Issue by hosembafer** [codebrainz/ftplib#2]
I use the original ftplib in my project and now in my needs make it to work on Windows. In this repo is there any modifications for that, or only changes for Autotools?

Sorry for my English.

**Comment by codebrainz** [comment]
At a glance, the code appears to be portable, what doesn't work on Windows?

I only made meta/build system changes though, no code improvements.

**Comment by hosembafer** [comment]
Thank you for response.

At the moment I haven't try compile it for Windows (I have global problem about compiling in Windows), but in the original list of supported OS there is no Windows.

**Comment by codebrainz** [comment]
I assume it would work if compiled with GCC and friends (ex. msys2) on Windows without much effort.
